[profile.default]
    src = "src"
    out = "out"
    evm_version = "paris"
    solc_version = "0.8.23"
    verbosity = 3
    ffi = false
    libs = ["lib"]
    optimizer = true
    optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
    mumbai = "${MUMBAI_RPC_URL}"
    sepolia = "${SEPOLIA_RPC_URL}"
    basesepolia = "${BASE_SEPOLIA_RPC_URL}"
    base = "${BASE_RPC_URL}"
    ethereum = "${ETH_RPC_URL}"
    arbitrum = "${ARBITRUM_RPC_URL}"
    arbitrumsepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
    mumbai = { key = "${POLYGONSCAN_API_KEY}", chain = "mumbai" }
    sepolia = { key = "${ETHERSCAN_API_KEY}" }